axf/app/urls.py
from django.conf.urls import url
from app import views
from rest_framework.routers import SimpleRouter

#
# router = SimpleRouter()
# router.register(r'goods', views.GoodsInfo)

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^login/', views.login, name='login'),
    # 注册
    url(r'^regist/', views.regist, name='regist'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^market/$', views.user_market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.market_params, name='marketparams'),

    # 添加购物车
    url(r'^addgoods/', views.add_goods, name='addgoods'),
    url(r'^subgoods/', views.sub_goods, name='subgoods'),
    # 购物车
    url(r'cart/', views.cart, name='cart'),
    # 修改购物车商品的选择
    url(r'^changecartselect/', views.user_change_select, name='change_select'),
    # 下单
    url(r'^generateorder/', views.generate_order, name='generate_order'),
    # 付款
    url(r'^payorder/(\d+)/', views.pay_order, name='pay_order'),
    # 确认付款
    url(r'^orderpayed/(\d+)/', views.order_pay, name='order_pay'),
    url(r'^orderwaitpay/', views.order_wait_pay, name='order_wait_pay'),
    # 待收货
    url(r'orderpay/', views.order_wait_shouhuo, name='order_wait_shouhuo'),
]

# urlpatterns += router.urls

axf/axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from axf import settings
from django.conf.urls.static import static
from django.views.static import serve
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
    # url(r'^static/(?P<path>.*)$', serve, {"docunment_root": settings.STATIC_ROOT}),
    # url(r'^$', views.home)

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

axf/app/models.py
from django.db import models

# Create your models here.


class Main(models.Model):
    img = models.CharField(max_length=200)  # 图片
    name = models.CharField(max_length=100)  # 名称
    trackid = models.CharField(max_length=16)  # 通用id

    class Meta:
        abstract = True


class MainWheel(Main):
    # 轮循 banner
    class Meta:
        db_table = 'axf_wheel'


class MainNav(Main):
    # 导航
    class Meta:
        db_table = 'axf_nav'


class MainMustBuy(Main):
    # 必购
    class Meta:
        db_table = 'axf_mustbuy'


class MainShop(Main):
    # 商店
    class Meta:
        db_table = 'axf_shop'


# 主要商品
class MainShow(Main):
    '''
    编号 id
    分类名称 name
    分类图片 img
    图片1 img1
    名称1 longname1
    优惠价格1 price1
    原始价格1 marketprice1
    图片2 img2
    名称2 longname2
    优惠价格2 price2
    原始价格2 marketprice2
    图片3 img3
    名称3 longname3
    优惠价格3 price3
    原始价格3 marketprice3
    '''
    categoryid = models.CharField(max_length=16)
    brandname = models.CharField(max_length=100)
    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=16)
    productid1 = models.CharField(max_length=16)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField(default=0)
    marketprice1 = models.FloatField(default=1)
    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField(default=0)
    marketprice2 = models.FloatField(default=1)
    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField(default=0)
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = 'axf_mainshow'


# 左侧类型表
class FoodType(models.Model):
    typeid = models.CharField(max_length=16)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_foodtypes'


class Goods(models.Model):
    '''
    编号       id            integer
    商品id     productid    integer
    商品图片   productimg
    商品名称   productname
    商品规格   productlongname
    规格      specifics
    折后价格   price
    原价       marketprice
    分类id     categoryid
    子分类id     childcid
    子id名称     childcidname
    排序       storenums
    销量       productnum
    '''
    productid = models.CharField(max_length=16)
    productimg = models.CharField(max_length=200)
    productname = models.CharField(max_length=100)
    productlongname = models.CharField(max_length=200)
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    marketprice = models.FloatField(default=1)
    categoryid = models.CharField(max_length=16)
    childcid = models.CharField(max_length=16)
    childcidname = models.CharField(max_length=100)
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)
    productnum = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_goods'


class UserModel(models.Model):
    '''
    username   名称
    password   密码
    email      邮箱
    sex        性别
    icon       头像
    is_delete  是否删除
    '''
    username = models.CharField(max_length=32, unique=True)
    password = models.CharField(max_length=256)
    email = models.CharField(max_length=64, unique=True)
    sex = models.BooleanField(default=False)
    icon = models.ImageField(upload_to='icons')
    is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = 'axf_users'


class UserTicket(models.Model):
    user = models.ForeignKey(UserModel)
    ticket = models.CharField(max_length=255, null=True)
    out_time = models.DateTimeField()

    class Meta:
        db_table = 'axf_ticket'


# 购物车
class CartModel(models.Model):
    '''
    user   关联用户
    goods  关联商品
    c_num  商品个数
    is_select  是否选择商品
    '''
    user = models.ForeignKey(UserModel)
    goods = models.ForeignKey(Goods)
    c_num = models.IntegerField(default=1)
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'axf_cart'


class OrderModel(models.Model):
    '''
    user       关联用户
    o_num      数量
    o_status   状态
    o_create   订单创建时间
    '''
    user = models.ForeignKey(UserModel)
    o_num = models.CharField(max_length=64)
    # 0代表已下单，但是未付款，1已付款未发货，2已付款已发货
    o_status = models.IntegerField(default=0)
    o_create = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'axf_order'


class OrderGoodsModel(models.Model):
    '''
    goods     关联的商品
    order     关联的订单
    good_num  商品的个数
    '''
    goods = models.ForeignKey(Goods)
    order = models.ForeignKey(OrderModel)
    goods_num = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_order_goods'

axf/templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="order_info" class="container">

    <!--订单编号-->
    <h3>订单编号:{{ order_id }}</h3>
    <!--处理结束-->
    <ul>

        <!--所有订单信息展示-->
        {% for ordergood in orders.ordergoodsmodel_set.all %}
            <li>
                <!--商品名称展示-->
                <img src="{{ ordergood.goods.productimg }}">

                <span> <!-- 数量展示 -->{{ ordergood.good_num }}</span>
            </li>
{% endfor %}
        <!--订单处理结束-->

    </ul>
        <!--订单id展示-->
        <button id="alipay"> <a href="{% url 'axf:order_pay' order_id %} ">Alipay</a></button>

    </div>


{% endblock %}

axf/templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>

    <ul>
        <!--订单展示-->
        {% for order in orders %}
            <li>
                <a href="#">
                    <p><!-- 订单id -->订单ID：{{ order.id }}</p>
                    {% for ordergoods in order.ordergoodsmodel_set.all %}
                    <p><!-- 数量 -->数量：{{ ordergoods.goods_num  }}</p>
                        <!--展示商品的名称-->
                        <li>
                            <img src="{{ ordergoodsl.goods.productimg }}" alt="">
                        </li>
                        <!--处理结束-->
                        {% endfor %}
                </a>
            </li>
        {% endfor %}
        <!--订单处理结束-->

    </ul>


{% endblock %}

axf/templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待付款订单列表</h3>

    <ul>
        <!--订单信息展示-->
        {% for order in orders %}
            <div style="height:4px; width:100%; "></div>
            <li>
                <a href="{% url 'axf:order_pay' order.id %}">
                    <p><!-- 订单id -->订单id：{{ order.id }}</p>
                    {% for ordergoods in order.ordergoodsmodel_set.all %}
                    <p><!-- 数量 -->数量：{{ ordergoods.goods_num }}</p>
                        <!--展示商品的名称-->
                        <li>
                            <img src="{{ ordergoods.goods.productimg }}" alt="">
                        </li>
                        <!--处理结束-->
                        {% endfor %}
                </a>
            </li>
        {% endfor %}
        <!--订单处理结束-->


    </ul>


{% endblock %}