axf/app/urls.py
from django.conf.urls import url
from app import views
from rest_framework.routers import SimpleRouter

#
# router = SimpleRouter()
# router.register(r'goods', views.GoodsInfo)

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^login/', views.login, name='login'),
    # 注册
    url(r'^regist/', views.regist, name='regist'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^market/$', views.user_market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.market_params, name='marketparams'),

    # 添加购物车
    url(r'^addgoods/', views.add_goods, name='addgoods'),
    url(r'^subgoods/', views.sub_goods, name='subgoods'),
    # 购物车
    url(r'cart/', views.cart, name='cart'),
    # 修改购物车商品的选择
    url(r'^changecartselect/', views.user_change_select, name='change_select'),
    # 下单
    url(r'^generateorder/', views.generate_order, name='generate_order'),
    # 付款
    url(r'^payorder/(\d+)/', views.pay_order, name='pay_order'),
    # 确认付款
    url(r'^orderpayed/(\d+)/', views.order_pay, name='order_pay'),
    url(r'^orderwaitpay/', views.order_wait_pay, name='order_wait_pay'),
    # 待收货
    url(r'orderpay/', views.order_wait_shouhuo, name='order_wait_shouhuo'),
]

# urlpatterns += router.urls

axf/axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from axf import settings
from django.conf.urls.static import static
from django.views.static import serve
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
    # url(r'^static/(?P<path>.*)$', serve, {"docunment_root": settings.STATIC_ROOT}),
    # url(r'^$', views.home)

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

axf/templates/cart/cart.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'app/cart/cart.css' %}">
{% endblock %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/cart/js/cart.js' %}"></script>
     <script type="text/javascript" src="{% static 'app/common/common.js' %}"></script>
{% endblock %}


{% block content %}

    <div id="cart">

        <h3>购物车</h3>

        <div class="full">

            <section class="clear">
                <ul>
                    <li>收货人:王帅帅<div><p><span><a href="#">修改&gt;</a></span></p></div></li>
                    <li>电话:8008208820 </li>
                    <li>收货地址:宝胜北里西区28号天丰利商城</li>

                </ul>


                <div class="bill">

                    <p>闪送超市</p>

                    <a href="#">凑单专区</a>

                    <p>满100减99</p>

                </div>

                <p class="delivery">

                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可送达&gt;</a>
                </p>

                <p class="delivery">
                    <span>留言:</span>
                    <input type="text" placeholder="有什么特殊需求">
                </p>


                <menu>

                    <ul>
                        <!--购物车信息展示-->
                        {% for cart in carts %}
                            <li class="menuList" cartid="">
                                <div class="confirm">
                                    <span id="changeselect_{{ cart.id }}" >
                                        {% if cart.is_select %}

                                            <span onclick="cartchangeselect({{ cart.id }})">√</span>
                                        {% else %}

                                            <span onclick="cartchangeselect({{ cart.id }})">x</span>

                                        {% endif %}


                                    </span>
                                </div>
                                <a href="#">
                                    <img src="{{ cart.goods.productimg}}" alt="">
                                    <p>{{ cart.goods.productlongname }}</p>
                                      <span>¥{{ cart.goods.price }}</span>
                                </a>
                                <section>
                                    {% csrf_token %}
                                    <button onclick="subShop({{ cart.goods.id }})" >-</button>
                                    <span id="num_{{ cart.goods.id }}">{{cart.c_num }}</span>
                                    <button onclick="addShop({{ cart.goods.id }})">+</button>
                                </section>
                            </li>
                        {% endfor %}
                        <!--购物车数据处理结束-->


                        <li class="payTheBill">

                            <div class="confirm" id="all_select" onclick="">

                                <span>

                                        <span>√</span>

                                        <span></span>

                                </span>
                            </div>

                            <p>
                                <span>全选</span>

                                <span id="price_total">{{ price_total }}</span>
                            </p>

                            <span><a href="{% url 'axf:generate_order' %}">下单</a></span>

                        </li>

                    </ul>

                </menu>

{#            <div class="menuList">#}
{##}
{#                {% for cart in carts %}#}
{##}
{#                    <div class="confirm">#}
{#                    <span>#}
{#                        <span>√</span>#}
{#                    </span>#}
{#                    </div>#}
{##}
{#                    <a href="#">#}
{#                        <img src="{{ cart.goods.productimg }}" alt="{{ cart.goods.productlongname }}">#}
{#                        <p>{{ cart.goods.productlongname }}</p>#}
{#                    </a>#}
{##}
{#                {% endfor %}#}
{##}
{##}
{#            </div>#}
            </section>



        </div>


    </div>


{% endblock %}